version: '3.8'

services:
  # Servicio principal de la aplicación
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sistema-notificacion-altas-bajas
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_PATH=/app/storage/db/database.sqlite
      - STORAGE_PATH=/app/storage
      - TZ=Europe/Paris
      # Variables para configuración de correo (personalizar según necesidades)
      - SMTP_HOST=${SMTP_HOST:-smtp.office365.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_SECURE=${SMTP_SECURE:-false}
      - SMTP_USER=${SMTP_USER:-diversifica.ia@outlook.es}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-password}
    volumes:
      - app-data:/app/storage
    networks:
      - app-network
    entrypoint: ["/app/docker-entrypoint.sh"]
    command: ["npm", "start"]

# Volúmenes para persistencia de datos
volumes:
  app-data:
    driver: local

# Redes para comunicación entre contenedores
networks:
  app-network:
    driver: bridge
